### ISSUE TITLE
NVM Docs improvements #2

### ISSUE THREAD

**Issue by aaitor** [keyko-io/nevermined-docs#63]
- [x] We must have good documentation about the search queries
- [x] https://github.com/nevermined-io/internal/issues/246
- [x] #64
- [x] #65
- [x] #66
- [x] #67
- [ ] #68
- [ ] #69
- [ ] #70
- [x] #71
- [x] #72
- [x] #73
- [x] #74
- [x] #75
- [x] #76
- [x] #77
- [x] #78
- [x] #79
- [x] #80
- [x] #81
- [x] #82
- [x] #83
- [x] #84
- [ ] Write a blog post to introduce the new docs website
- [x] #86
- [x] Have a _**Nevermined Docs**_ logo instead of just text similar to top-left https://ionicframework.com/docs
- [x] #85

## Look & Feel

- [ ] This doesn't have any sense
